SQLConnectionString: postgres://dbuser:pass@127.0.0.1:5432/db?sslmode=disable
# Should it run forever and clean every interval?
# If this is false the program will stop after cleaning once (aka. cronjob-mode)
RunAsDaemon: false
# If RunAsDaemon is true, the cleanup will happen every X minutes
DaemonRunInterval: 1440
# This deletes any documents after the configured time, sql:
# DELETE FROM docs WHERE timestamp > CURRENT_TIMESTAMP - '$MaxAgeForAll'
EnableMaxAgeCleaning: true
MaxAgeForAll: "90 days"
# "Cleanup" searches in docs for Key:Value matches and deletes them if older than KeepFor
Cleanup:
    - Key: _meta.group
      Value: web
      KeepFor: "30 days"
    - Key: _meta.group
      Value: k8s
      KeepFor: "60 days"
